export default {
    lang: 'EN',
    navbarLink1: 'Home',
    navbarLink2: 'Projects',
    navbarLink3: 'Resume',
    navbarLink4: 'Contact',
    presentation: "Hi, i'm Leandro, a front-end developer!.",
    presentation2: "I'm a guy from Venezuela, I've been programming using Front-end technologies like React, Redux, Next and Vue for almost a year, writing code is something I really love to do, and it keeps me learning new things every day.",
    projectsHeader: 'My Projects',
    taskManagerSubt: 'Create, read and delete tasks!',
    taskManagerDesc: 'This is a web app where you can manage tasks, you can create, edit and eliminate a task by using a form. It was built using React alongside Typescript, and Firebase for the REST API where the tasks are keep.',
    countriesAppSubt: 'Learn about all the countries of the world!',
    countriesAppDesc: 'This is a web where you are able to see all the countries of the world, their flags and info by clicking in the country of your choice.',
    rockPaperScissorsSubt:'Have fun playing rock paper scissors!',
    rockPaperScissorsDesc:"In this simple but funny rock paper scissors app you are going to be able to play againts the machine and saving your score by winning, you can also download it since it's a pwa.",
    spaceTourismWebSubt:'Travel across the universe!',
    spaceTourismWebDesc:'This is a web where you can "travel" trough space and learn about it, it was made using Gatsby alongside Typescript and Styled-components.',
    cardsCodeBtn:'Code',
    formHeader: 'Contact Me',
    formInp1: 'Your Name',
    formInp2: 'Your Email Adress',
    formInp3: 'Message',
    formBtn: 'SEND MESSAGE'
}