export default {
    lang: 'ES',
    navbarLink1: 'Inicio',
    navbarLink2: 'Proyectos',
    navbarLink3: 'Resumen',
    navbarLink4: 'Contacto',
    presentation:'Hola, soy Leandro, un desarrolador front-end web!.',
    presentation2:'Soy un chico de Venezuela, he estado programando usando tecnologías Front-end como React, Redux, Next y Vue durante casi un año,escribir codigo es algo que realmente me encanta hacer, y eso me mantiene aprendiendo cosas nuevas todos los días.',
    projectsHeader: 'Mis Proyectos',
    taskManagerSubt: 'Crea, lee y edita tus tareas!',
    taskManagerDesc: 'En esta web puedes administrar tareas, puedes crear, editar y eliminar una tarea a traves de un formulario. Fue hecha usando React junto a Typescript y Firebase para la API REST donde se guardan las tareas.',
    countriesAppSubt: 'Aprende sobre los paises del mundo!',
    countriesAppDesc: 'Esta es una web donde puedes ver todos los países del mundo, sus banderas e información haciendo clic en el país de tu elección.',
    rockPaperScissorsSubt:'Diviertete jugando piedra, papel o tijeras!',
    rockPaperScissorsDesc:'En esta sencilla pero divertida aplicación de piedra, papel o tijera vas a poder jugar contra la máquina y guardar tu puntuación al ganar, también puedes descargarla ya que es una pwa.',
    spaceTourismWebSubt:'Viaja a traves del universo!',
    spaceTourismWebDesc:'Esta es una web donde puedes "viajar" por el espacio y aprender sobre él, fue hecha usando Gatsby junto Typescript y Styled-components.',
    cardsCodeBtn:'Codigo',
    formHeader:'Contáctame',
    formInp1: 'Nombre',
    formInp2: 'Email',
    formInp3: 'Mensaje',
    formBtn: 'ENVIAR'
}